### ISSUE TITLE
Read on face detection and identify appropriate image dataset

### ISSUE THREAD

**Issue by cotemyriam** [nouiz/lisa_emotiw#21]
Start on face detection: read Henry Rowley's paper "Neural Network based face detection"

and identify large image dataset with labeled face bounding boxes (other than the ones listed above).

**Comment by caglar** [comment]
I've read the paper, I can give a small tea-talk after the ICLR conference.

The datasets that I could find are:

Automatic Naming of Characters in TV Video: http://www.robots.ox.ac.uk/~vgg/research/nface/
Face Detection Data Set and Benchmark Home: http://vis-www.cs.umass.edu/fddb/
YouTube Celebrities Face Tracking and Recognition Dataset: http://seqam.rutgers.edu/site/index.php?option=com_content&view=article&id=64&Itemid=80
Face tracer dataset: http://www.cs.columbia.edu/CAVE/databases/facetracer/
Face in Action dataset: http://www.flintbox.com/public/project/5486/ (You have to pay for that-not much info on their page)
LFWcrop: Face Dataset http://itee.uq.edu.au/~conrad/lfwcrop/ (LFWcrop is a cropped version of the Labeled Faces in the Wild (LFW) dataset, keeping only the center portion of each image (i.e. the face). In the vast majority of images almost all of the background is omitted.)
