### ISSUE TITLE
Aggregation: Bidirectional recurrent network

### ISSUE THREAD

**Issue by yoshua** [nouiz/lisa_emotiw#5]
Code up a bidirectional recurrent network in Theano, with fixed-pooling (e.g. max-pooling or another of the fixed aggregation methods) to produce a vector of per-emotion probabilities.

Unit-test it on artificial data.

Test on the single-frame classifier outputs.

**Comment by pascanur** [comment]
There is code for bi-RNN in emotiw/pascanur (birnn.py) 

There is a script also to run the model using SGD for the audio files (which stands for the unit -test on artificial data)
