### ISSUE TITLE
Simple feature extraction (MFCC) from speech on current data

### ISSUE THREAD

**Issue by yoshua** [nouiz/lisa_emotiw#6]
Use existing libraries for extracting spectral features from audio and compute these features on the challenge data.

**Comment by dwf** [comment]
George Dahl's preprocessing for speech data is log mel-scale filterbanks,
basically the MFCCs before the cepstral transform, on 25ms windows shifted
by either 5ms or 10ms. It would be good to have this preprocessing handy as
well.

**Comment by boulanni** [comment]
Pretty much done, see https://github.com/nouiz/lisa_emotiw/wiki/06.-Emotion-Classification-from-Speech

**Comment by yoshua** [comment]
Please close the ticket when done.
